### ISSUE TITLE
error generating files

### ISSUE THREAD

**Issue by joggs** [boralyl/cookiecutter-homeassistant-component#1]
I am getting the following error running cookiecutter in a windows environment after entering the final option in the wizard:

  Choose from 1, 2 [1]:
Select iot_class:
1 - Assumed State
2 - Cloud Polling
3 - Cloud Push
4 - Local Polling
5 - Local Push
Choose from 1, 2, 3, 4, 5 [1]:
Traceback (most recent call last):
  File "c:\users\j\appdata\local\temp\tmpqwx1ms.py", line 6, in <module>
    os.rename(os.path.join("..", repo_dir), os.path.join("..", new_repo_dir))
WindowsError: [Error 32] The process cannot access the file because it is being used by another process
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)

**Comment by boralyl** [comment]
I'm not super familiar with running python on Windows, but the error message seems to imply another process is using the folder that `cookiecutter` is attempting to rename.  Could you make sure you don't have the repository that was cloned opened in a folder or another program when running the cookiecutter command?

If you are still having issues, I'd suggest opening up an issue on the [cookiecutter](https://github.com/cookiecutter/cookiecutter) repository as this repository is just a template and doesn't include any of the code for generating the directories.

**Comment by joggs** [comment]
Thanks for the suggestions!
