### ISSUE TITLE
Permission error

### ISSUE THREAD

**Issue by stigvi** [boralyl/cookiecutter-homeassistant-component#2]
The error message is in Norwegian, but it says the the process cannot access the file because it is used by another process.

`D:\Kladd\e>cookiecutter https://github.com/boralyl/cookiecutter-homeassistant-component
domain [my_component]: elprice
name [My Component]: ElPrice
docs_url [https://github.com/user/my_component/]:
owner [@user]: @stigvi
Select config_flow:
1 - yes
2 - no
Choose from 1, 2 [1]: 2
Select iot_class:
1 - Assumed State
2 - Cloud Polling
3 - Cloud Push
4 - Local Polling
5 - Local Push
Choose from 1, 2, 3, 4, 5 [1]: 1
Traceback (most recent call last):
  File "C:\Users\STIGVI~1.HEI\AppData\Local\Temp\tmpz14vwgnu.py", line 6, in <module>
    os.rename(os.path.join("..", repo_dir), os.path.join("..", new_repo_dir))
PermissionError: [WinError 32] Prosessen får ikke tilgang til filen fordi den brukes av en annen prosess: '..\\elprice' -> '..\\elprice'
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)

D:\Kladd\e>`

**Comment by boralyl** [comment]
I'm not super familiar with python on Windows, but can't reproduce the issue locally on linux.  Can you make sure you don't have a file browser or other application open that might be accessing that folder?

**Comment by boralyl** [comment]
Also make sure that destination doesn't already exist.

**Comment by SondreNjaastad** [comment]
@stigvi , Where you able to solve this? I have the same issue

**Comment by boralyl** [comment]
@SondreNjaastad are you also using Windows?

**Comment by SondreNjaastad** [comment]
Yes

**Comment by boralyl** [comment]
I looked into this a bit, but couldn't figure out the root problem.  The renaming that happens here is really a cosmetic thing, so I've updated the repo to skip this step for Windows.  That should allow your project to be created now.
