### ISSUE TITLE
Not related to cookiecutter-homeassistant-component

### ISSUE THREAD

**Issue by NoiseGenerated** [boralyl/cookiecutter-homeassistant-component#3]
Hello, I could not find any other way of sending you a message so I will try here, is this tutorial still useable with all the changes from the last time the tutorial got updated? It says **August 2, 2019**

https://aarongodfrey.dev/home%20automation/creating-a-3d-floorplan-in-home-assistant/

**Comment by boralyl** [comment]
Yes, that tutorial still works for the current version, 2021.8.8.  If you have other questions you can reach out on the community thread: https://community.home-assistant.io/t/3d-floorplan-using-lovelace-picture-elements-card/123357
