### ISSUE TITLE
Cannot install dependencies & run test suite

### ISSUE THREAD

**Issue by wbyoung** [boralyl/cookiecutter-homeassistant-component#6]
This could be related to some recent updates, but I'm getting the following issues:

* Can't install the dependencies with `pip install -r requirements.test.txt --upgrade` because of `ERROR: Cannot install -r requirements.test.txt (line 3) and pytest-cov==2.9.0 because these package versions have conflicting dependencies.`, see
[pip-output.txt](https://github.com/user-attachments/files/15934146/pip-output.txt) for full output. Once the versions of `pytest-cov` is unpinned, install can proceed, but perhaps that leads to later issues.
* `pytest` fails to test anything with the following output:
```tests/test_init.py::test_async_setup
  /Users/wbyoung/Code/watersmart/venv/lib/python3.12/site-packages/_pytest/python.py:151: PytestUnhandledCoroutineWarning: async def functions are not natively supported and have been skipped.
  You need to install a suitable plugin for your async framework, for example:
    - anyio
    - pytest-asyncio
    - pytest-tornasync
    - pytest-trio
    - pytest-twisted
    warnings.warn(PytestUnhandledCoroutineWarning(msg.format(nodeid)))
```
* Once `asyncio_mode = auto` is added to the `[tool:pytest]` section of `setup.cfg`, tests proceed, but the setup is never invoked and `stderr` includes the following: `ERROR:homeassistant.setup:Setup failed for 'watersmart': Integration not found.`.

Any suggestions on how to proceed?

**Comment by wbyoung** [comment]
It looks like I was just missing the autoload of the fixture to enable custom integrations.

The simple version provided in the example for `pytest-homeassistant-custom-component` is to add [`tests/conftest.py`](https://github.com/MatthewFlamm/pytest-homeassistant-custom-component/blob/master/tests/conftest.py):

```python
"""Fixtures for testing."""

import pytest


@pytest.fixture(autouse=True)
def auto_enable_custom_integrations(enable_custom_integrations):
    """Enable custom integrations."""
    return
```

**Comment by boralyl** [comment]
Thanks @wbyoung , I believe https://github.com/boralyl/cookiecutter-homeassistant-component/commit/e27d236b058fb508dfac917c9f1878a3df096132 adds the required  changes based on your comments above.

**Comment by wbyoung** [comment]
Looks good. Thanks! Maybe also double check the pinned dependencies, but hopefully this helps someone else!

**Comment by boralyl** [comment]
> Looks good. Thanks! Maybe also double check the pinned dependencies, but hopefully this helps someone else!

You're right, I forgot about the pinned deps, I'll take a look at resolving that.
