### ISSUE TITLE
Consider loading syrupy early

### ISSUE THREAD

**Issue by wbyoung** [boralyl/cookiecutter-homeassistant-component#7]
I ran into an issue with `pytest-homeassistant-custom-component`, https://github.com/MatthewFlamm/pytest-homeassistant-custom-component/issues/198.

Would it be worthwhile to add [`-p syrupy` here](https://github.com/boralyl/cookiecutter-homeassistant-component/blob/581cec1a55f5d548382804ddd32c792594c7135c/%7B%7B%20cookiecutter.domain%20%7D%7D/setup.cfg#L18)?

**Comment by boralyl** [comment]
Interesting, I hadn't come across this before.  Thanks for bringing it to my attention. This seems like a fine workaround for now.

**Comment by boralyl** [comment]
https://github.com/boralyl/cookiecutter-homeassistant-component/commit/2272ae764843d1361544dea94b526e196443aedf
